#!/usr/bin/ruby	

require 'net/https'
require 'rexml/document'	

abort("Usage: vote-on-bundle <repository id> [<repository id>]") unless ARGV.length >= 1

REPO_ID=ARGV[0]
START_URL="https://repository.apache.org/service/local/repositories/#{REPO_ID}/content/org/apache/servicemix/bundles/"

def get(url) 
  uri = URI.parse(url)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  request = Net::HTTP::Get.new(uri.request_uri)

  response = http.request(request)
  REXML::Document.new(response.body)
end 

def findGAVs
  ARGV.each { |repo|
    puts "Reading GAV information from the repository #{repo}"
    url="https://repository.apache.org/service/local/repositories/#{repo}/content/org/apache/servicemix/bundles/"
    get(url).elements.each('content/data/content-item[leaf="false"]') do |item|
      artifactId=item.elements["text"].text
      get(item.elements["resourceURI"].text).elements.each('content/data/content-item[leaf="false"]') do |version|
        version=version.elements["text"].text
        yield "org.apache.servicemix.bundles", artifactId, version
      end
    end
  }
end 

mvn_urls=Array.new
tags=Array.new


findGAVs { |groupId, artifactId, version| 
  puts "- found bundle #{artifactId} #{version}"
  mvn_urls << "mvn:#{groupId}/#{artifactId}/#{version}"
  tags << "#{artifactId}-#{version}"
}

puts
puts "To install the staged bundles in Karaf, use these commands:"
puts "-----------------------------------------------------------"
mvn_urls.each { |url|
  puts "osgi:install -s #{url}"
}

puts 
puts "You can build the tags from your Git repository with these command:"
puts "-------------------------------------------------------------------"
tags.each { |tag|
  puts "git checkout #{tag}"
  puts "mvn clean install"
}